model:
  checkpoint_path: "./models/Illustrious-XL-v2.0.safetensors"
  pretrained_model_name_or_path: cagliostrolab/animagine-xl-4.0

  dtype: bfloat16

  denoiser:
    attn_implementation: "flash_attention_2"

  adapter: # ip-adapter
    ip_scale: 1.0
    num_ip_tokens: 8
    image_size: 384
    background_color: 0 # 0 for black, 255 for white

    projector_type: "mlp" # linear, mlp, resampler
    projector_args:
      mlp_ratio: 4.0

    # checkpoint_weight: null
    image_encoder:
      type: timm
      model_name: "hf_hub:timm/vit_base_patch16_siglip_384.v2_webli"

    image_mean: [0.5, 0.5, 0.5]
    image_std: [0.5, 0.5, 0.5]
    color_channel: rgb # bgr for wd-tagger

    feature_dim: 768

  # training config
  max_token_length: 75

peft:

dataset:
  folder: "data/sfw_0.1k"

  num_repeats: 1
  batch_size: 1

  bucket_base_size: 1024
  step: 128
  min_size: 384
  do_upscale: false

  caption_processors:
    - type: shuffle
      split_separator: ","
    - type: tag_drop
      separator: ","
      drop_rate: 0.5
    - type: drop
      drop_rate: 0.1

optimizer:
  name: "schedulefree.RAdamScheduleFree"
  # name: "bitsandbytes.optim.AdamW8bit"
  args:
    lr: 0.001

scheduler:
  # name: "torch.optim.lr_scheduler.ConstantLR"
  # args: {}

tracker:
  project_name: "sdxl-pfg-1"
  loggers:
    - wandb

saving:
  strategy:
    per_epochs: 1
    per_steps: null
    save_last: true

  callbacks:
    - type: "safentensors" # or "hf_hub" to push to hub
      name: "sdxl-pfg-1"
      save_dir: "./output/sdxl-pfg-1"

preview:
  strategy:
    per_epochs: 1
    per_steps: null

  callbacks:
    - type: "local"
      save_dir: "./output/sdxl-pfg-1/preview"

  data:
    path: "./configs/sdxl/prompt_free/preview.yml"

seed: 42
num_train_epochs: 10

trainer:
  # debug_mode: "1step"

  gradient_checkpointing: true
  gradient_accumulation_steps: 1

  clip_grad_norm: 1.0
  # clip_grad_value: 1.0

  torch_compile: false
  torch_compile_args:
    backend: eager
    mode: default
    fullgraph: false
  fp32_matmul_precision: "high"
