- prompt: |-
    1girl, solo, upper body, looking at viewer, 
    masterpiece, extremely aesthetic, newest, very vibrant colors, <|style|>
  negative_prompt: |-
    worst quality, low quality, lowers, low details, bad quality, poorly drawn, 
    bad anatomy, multiple views, bad hands, blurry, artist sign, weibo username
  width: 1024
  height: 1536
  cfg_scale: 7.5
  num_steps: 25

  seed: 0

  extra:
    reference_image_path: ./assets/sample_01.jpg
