model:
  num_pixels: 784
  hidden_dim: 128
  num_labels: 10

dataset:
  repo_id: "ylecun/mnist"

optimizer:
  name: "schedulefree.RAdamScheduleFree"
  args:
    lr: 0.0005

scheduler:
#   name: "torch.optim.lr_scheduler.ConstantLR"
#   args: {}

trackers:
  - name: wandb
    args:
      project: "mnist-1"

saving:
  strategy:
    per_epochs: 5
    per_steps: null
    save_last: true

  callbacks:
    - type: "hf_hub"
      name: "mnist"
      save_dir: "./output/mnist-schedulefree"
      hub_id: "p1atdev/test"
      dir_in_repo: "/mnist-schedulefree"

seed: 42
num_train_epochs: 10

torch_compile: false
fp32_matmul_precision: "high"
