- prompt: |-
    1girl, aqua eyes, baseball cap, blonde hair, closed mouth, earrings, 
    green background, hat, hoop earrings, jewelry, looking at viewer, 
    shirt, short hair, simple background, solo, upper body, yellow shirt
  negative_prompt: "blurry, ugly, low quality"
  height: 1024
  width: 1024
  cfg_scale: 5.0
  num_steps: 20

  seed: 1

- prompt: photo of a cat
  negative_prompt: "blurry, ugly, low quality"
  height: 1024
  width: 1024
  cfg_scale: 5.0
  num_steps: 20

  seed: 1
